# Use an official Node.js runtime as the base image
FROM node:14 AS server

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY server/package*.json ./

# Install app dependencies
RUN npm install

# Copy all the app's source code to the working directory
COPY server/ .

# Expose the port the server will listen on
EXPOSE 3005

# Command to run the Express server
CMD ["npm", "start"]
