version: "3.8"

services:
  server-glitchandbooks:
    build: .
    container_name: server-glitchandbooks
    env_file:
      - .env
    depends_on:
      - server-db-glitchandbooks
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}

  server-db-glitchandbooks:
    image: postgres:13
    container_name: server-db-glitchandbooks
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata-glitchandbooks:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped

volumes:
  pgdata-glitchandbooks:
