version: "3"
services:
  client:
    image: ericphil/glitchandbooks-client:latest
    ports:
      - "80:80"
    env_file:
      - .env.client

  server:
    image: ericphil/glitchandbooks-server:latest
    ports:
      - "3005:3005"
    env_file:
      - .env.server
