version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    env_file:
      - client/.env

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3005:3005"
    env_file:
      - server/.env
