name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t glitchandbooks .

      - name: Tag Docker image
        run: docker tag glitchandbooks ${{ secrets.DOCKER_USERNAME }}/glitchandbooks-server

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/glitchandbooks-server
