name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Client Docker image
        working-directory: ./client
        run: |
          docker build -t ericphil/glitchandbooks-client:latest .
          docker push ericphil/glitchandbooks-client:latest

      - name: Build and push Server Docker image
        working-directory: ./server
        run: |
          docker build -t ericphil/glitchandbooks-server:latest .
          docker push ericphil/glitchandbooks-server:latest
